.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -31,18 +31,22 @@ jobs:
           config: initializbuildpacks/${{ inputs.image }}/apko.yaml
           tag: initializbuildpacks/${{ inputs.image }}:latest
 
+      - name: Check if Docker image exists locally
+        run: |
+          if docker images initializbuildpacks/${{ inputs.image }}:latest | grep -q initializbuildpacks/${{ inputs.image }}; then
+            echo "Docker image initializbuildpacks/${{ inputs.image }}:latest found."
+          else
+            echo "Docker image initializbuildpacks/${{ inputs.image }}:latest not found. Please build the image first."
+            exit 1
+          fi
+
       - name: Tag and push Docker image to Docker Hub
         env:
           DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
           REPOSITORY: ${{ inputs.image }}
         run: |
-          if docker images initializbuildpacks/${{ inputs.image }}:latest | grep -q initializbuildpacks/${{ inputs.image }}; then
-            docker tag initializbuildpacks/${{ inputs.image }}:latest $DOCKERHUB_USERNAME/${{ inputs.image }}:latest
-            docker push $DOCKERHUB_USERNAME/${{ inputs.image }}:latest
-          else
-            echo "Docker image initializbuildpacks/${{ inputs.image }}:latest not found. Please build the image first."
-            exit 1
-          fi
+          docker tag initializbuildpacks/${{ inputs.image }}:latest initializbuildpacks/${{ inputs.image }}:latest
+          docker push initializbuildpacks/${{ inputs.image }}:latest
 
       - name: Install sigstore/cosign
         uses: sigstore/cosign-installer@v3.1.2
